name: Docker Image CI
env:
  IMAGE_TAG: my-image-name-$(date +%s)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_TAG && docker run $IMAGE_TAG pytest

